### ISSUE TITLE
Where can the AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [CityChainFoundation/city-hub#40]
https://github.com/CityChainFoundation/city-hub/blob/14287b6be9e4be3fd48b006582ab4b913bd7c9ec/.travis.yml#L64

Where can the AppImage be downloaded?

**Comment by sondreb** [comment]
Hi @probonopd and thanks for the interest! The remote Linux builder service was having issues last night so was unable to make a Linux-release. There are still issues right now. Unfortunately I deleted the preview release that had a Linux (AppImage) build on it.

When the CI setup with Travis and AppVeyor is complete, those services will be responsible for doing the build and publish. I'll keep you posted and we'll continue work on the CI-setup.

**Comment by sondreb** [comment]
The Linux installer using AppImage is now available in the releases: https://github.com/CityChainFoundation/city-hub/releases

I'm sure you already know how to run the .AppImage package, but for anyone else, here are the instructions in the README: https://github.com/CityChainFoundation/city-hub#linux-ubuntu
